//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym_Fitness.LicenseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenseRequest", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class LicenseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HDDField;
        
        private System.DateTime HistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HDD {
            get {
                return this.HDDField;
            }
            set {
                if ((object.ReferenceEquals(this.HDDField, value) != true)) {
                    this.HDDField = value;
                    this.RaisePropertyChanged("HDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime History {
            get {
                return this.HistoryField;
            }
            set {
                if ((this.HistoryField.Equals(value) != true)) {
                    this.HistoryField = value;
                    this.RaisePropertyChanged("History");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UndergraduateAnswer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UndergraduateAnswer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int VerificationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HDDField;
        
        private System.DateTime HistoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int VerificationCode {
            get {
                return this.VerificationCodeField;
            }
            set {
                if ((this.VerificationCodeField.Equals(value) != true)) {
                    this.VerificationCodeField = value;
                    this.RaisePropertyChanged("VerificationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HDD {
            get {
                return this.HDDField;
            }
            set {
                if ((object.ReferenceEquals(this.HDDField, value) != true)) {
                    this.HDDField = value;
                    this.RaisePropertyChanged("HDD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime History {
            get {
                return this.HistoryField;
            }
            set {
                if ((this.HistoryField.Equals(value) != true)) {
                    this.HistoryField = value;
                    this.RaisePropertyChanged("History");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Hash {
            get {
                return this.HashField;
            }
            set {
                if ((object.ReferenceEquals(this.HashField, value) != true)) {
                    this.HashField = value;
                    this.RaisePropertyChanged("Hash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LicenseService.LicenseKeySoap")]
    public interface LicenseKeySoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LicenseVerification", ReplyAction="*")]
        Gym_Fitness.LicenseService.LicenseVerificationResponse LicenseVerification(Gym_Fitness.LicenseService.LicenseVerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LicenseVerification", ReplyAction="*")]
        System.Threading.Tasks.Task<Gym_Fitness.LicenseService.LicenseVerificationResponse> LicenseVerificationAsync(Gym_Fitness.LicenseService.LicenseVerificationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LicenseVerificationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LicenseVerification", Namespace="http://tempuri.org/", Order=0)]
        public Gym_Fitness.LicenseService.LicenseVerificationRequestBody Body;
        
        public LicenseVerificationRequest() {
        }
        
        public LicenseVerificationRequest(Gym_Fitness.LicenseService.LicenseVerificationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LicenseVerificationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Gym_Fitness.LicenseService.LicenseRequest request;
        
        public LicenseVerificationRequestBody() {
        }
        
        public LicenseVerificationRequestBody(Gym_Fitness.LicenseService.LicenseRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LicenseVerificationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LicenseVerificationResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gym_Fitness.LicenseService.LicenseVerificationResponseBody Body;
        
        public LicenseVerificationResponse() {
        }
        
        public LicenseVerificationResponse(Gym_Fitness.LicenseService.LicenseVerificationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LicenseVerificationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Gym_Fitness.LicenseService.UndergraduateAnswer LicenseVerificationResult;
        
        public LicenseVerificationResponseBody() {
        }
        
        public LicenseVerificationResponseBody(Gym_Fitness.LicenseService.UndergraduateAnswer LicenseVerificationResult) {
            this.LicenseVerificationResult = LicenseVerificationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LicenseKeySoapChannel : Gym_Fitness.LicenseService.LicenseKeySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicenseKeySoapClient : System.ServiceModel.ClientBase<Gym_Fitness.LicenseService.LicenseKeySoap>, Gym_Fitness.LicenseService.LicenseKeySoap {
        
        public LicenseKeySoapClient() {
        }
        
        public LicenseKeySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LicenseKeySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenseKeySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenseKeySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gym_Fitness.LicenseService.LicenseVerificationResponse Gym_Fitness.LicenseService.LicenseKeySoap.LicenseVerification(Gym_Fitness.LicenseService.LicenseVerificationRequest request) {
            return base.Channel.LicenseVerification(request);
        }
        
        public Gym_Fitness.LicenseService.UndergraduateAnswer LicenseVerification(Gym_Fitness.LicenseService.LicenseRequest request) {
            Gym_Fitness.LicenseService.LicenseVerificationRequest inValue = new Gym_Fitness.LicenseService.LicenseVerificationRequest();
            inValue.Body = new Gym_Fitness.LicenseService.LicenseVerificationRequestBody();
            inValue.Body.request = request;
            Gym_Fitness.LicenseService.LicenseVerificationResponse retVal = ((Gym_Fitness.LicenseService.LicenseKeySoap)(this)).LicenseVerification(inValue);
            return retVal.Body.LicenseVerificationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gym_Fitness.LicenseService.LicenseVerificationResponse> Gym_Fitness.LicenseService.LicenseKeySoap.LicenseVerificationAsync(Gym_Fitness.LicenseService.LicenseVerificationRequest request) {
            return base.Channel.LicenseVerificationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gym_Fitness.LicenseService.LicenseVerificationResponse> LicenseVerificationAsync(Gym_Fitness.LicenseService.LicenseRequest request) {
            Gym_Fitness.LicenseService.LicenseVerificationRequest inValue = new Gym_Fitness.LicenseService.LicenseVerificationRequest();
            inValue.Body = new Gym_Fitness.LicenseService.LicenseVerificationRequestBody();
            inValue.Body.request = request;
            return ((Gym_Fitness.LicenseService.LicenseKeySoap)(this)).LicenseVerificationAsync(inValue);
        }
    }
}
